openapi: 3.0.1
info:
  title: oda-actions-service
  version: 1.0.0
paths:
  /actions:
    get:
      operationId: getActions
      parameters:
      - name: recipientId
        in: query
        required: true
        explode: false
        schema:
          type: string
      - name: game
        in: query
        explode: false
        schema:
          type: string
          nullable: true
      - name: enabled
        in: query
        explode: false
        schema:
          type: boolean
          nullable: true
      - name: category
        in: query
        explode: false
        schema:
          type: string
          nullable: true
      - name: provider
        in: query
        explode: false
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: getActions 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActionController.ActionDto"
  /actions/commands/addActions:
    post:
      operationId: addAction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddAction.AddActionsCommand"
        required: true
      responses:
        "200":
          description: addAction 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpResponse_List_AddAction.AddActionResult__"
  /actions/commands/deleteActions:
    post:
      operationId: deleteActions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteActions.DeleteActionsCommand"
        required: true
      responses:
        "200":
          description: deleteActions 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteActions.DeleteActionsResult"
  /actions/commands/disableActions:
    post:
      operationId: disableActions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DisableActions.DisableActionsCommand"
        required: true
      responses:
        "200":
          description: disableActions 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DisableActions.DisableActionsResult"
  /actions/commands/enableActions:
    post:
      operationId: enableActions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnableActions.EnableActionsCommand"
        required: true
      responses:
        "200":
          description: enableActions 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnableActions.EnableActionsResult"
components:
  schemas:
    ActionController.ActionDto:
      required:
      - category
      - enabled
      - game
      - id
      - name
      - payload
      - price
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          $ref: "#/components/schemas/Amount"
        category:
          type: string
        game:
          type: string
        enabled:
          type: boolean
        payload:
          type: object
          additionalProperties:
            type: object
    AddAction.ActionParameter:
      required:
      - displayName
      - name
      - type
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        type:
          type: string
    AddAction.AddActionResult:
      required:
      - action
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        action:
          $ref: "#/components/schemas/ActionController.ActionDto"
    AddAction.AddActionsCommand:
      required:
      - actions
      type: object
      properties:
        actions:
          type: array
          items:
            $ref: "#/components/schemas/AddAction.NewAction"
    AddAction.NewAction:
      required:
      - category
      - game
      - name
      - parameters
      - payload
      - price
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        game:
          type: string
        price:
          $ref: "#/components/schemas/Amount"
        payload:
          type: object
          additionalProperties:
            type: object
        parameters:
          type: array
          items:
            $ref: "#/components/schemas/AddAction.ActionParameter"
    Amount:
      required:
      - currency
      - major
      - minor
      type: object
      properties:
        minor:
          type: integer
          format: int32
        major:
          type: integer
          format: int32
        currency:
          type: string
    AttributeHolder:
      required:
      - attributes
      type: object
      properties:
        attributes:
          $ref: "#/components/schemas/ConvertibleValues_Object_"
    ConversionService:
      type: object
    ConversionServiceProvider:
      required:
      - conversionService
      type: object
      properties:
        conversionService:
          $ref: "#/components/schemas/ConversionService"
    ConvertibleMultiValues_String_:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConvertibleValues_List_String__"
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          empty:
            type: boolean
    ConvertibleValues_Cookie_:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          empty:
            type: boolean
          conversionService:
            $ref: "#/components/schemas/ConversionService"
    ConvertibleValues_List_String__:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          empty:
            type: boolean
          conversionService:
            $ref: "#/components/schemas/ConversionService"
    ConvertibleValues_Object_:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          empty:
            type: boolean
          conversionService:
            $ref: "#/components/schemas/ConversionService"
    Cookie:
      required:
      - name
      - value
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        domain:
          type: string
          nullable: true
        path:
          type: string
          nullable: true
        httpOnly:
          type: boolean
        secure:
          type: boolean
        maxAge:
          type: integer
          format: int64
        sameSite:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/SameSite"
    Cookies:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConvertibleValues_Cookie_"
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          all:
            type: array
            items:
              $ref: "#/components/schemas/Cookie"
    DeleteActions.DeleteActionsCommand:
      type: object
      properties:
        category:
          type: string
          nullable: true
        provider:
          type: string
          nullable: true
        ids:
          type: array
          nullable: true
          items:
            type: string
    DeleteActions.DeleteActionsResult:
      required:
      - ids
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        ids:
          type: array
          items:
            type: string
    DisableActions.DisableActionsCommand:
      type: object
      properties:
        category:
          type: string
          nullable: true
        provider:
          type: string
          nullable: true
        game:
          type: string
          nullable: true
        ids:
          type: array
          nullable: true
          items:
            type: string
    DisableActions.DisableActionsResult:
      required:
      - ids
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        ids:
          type: array
          items:
            type: string
    EnableActions.EnableActionsCommand:
      type: object
      properties:
        category:
          type: string
          nullable: true
        provider:
          type: string
          nullable: true
        game:
          type: string
          nullable: true
        ids:
          type: array
          nullable: true
          items:
            type: string
    EnableActions.EnableActionsResult:
      required:
      - ids
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        ids:
          type: array
          items:
            type: string
    Headers:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConvertibleMultiValues_String_"
      - $ref: "#/components/schemas/ConvertibleValues_List_String__"
      - $ref: "#/components/schemas/ConversionServiceProvider"
    HttpHeaders:
      type: object
      allOf:
      - $ref: "#/components/schemas/Headers"
      - $ref: "#/components/schemas/ConvertibleMultiValues_String_"
      - $ref: "#/components/schemas/ConvertibleValues_List_String__"
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          conversionService:
            $ref: "#/components/schemas/ConversionService"
          empty:
            type: boolean
          keepAlive:
            type: boolean
          origin:
            type: string
            nullable: true
          authorization:
            type: string
            nullable: true
          contentType:
            type: string
            nullable: true
    HttpMessage_List_AddAction.AddActionResult__:
      required:
      - attributes
      - body
      - characterEncoding
      - contentType
      - headers
      - locale
      type: object
      allOf:
      - $ref: "#/components/schemas/MutableAttributeHolder"
      - $ref: "#/components/schemas/AttributeHolder"
      - type: object
        properties:
          headers:
            $ref: "#/components/schemas/HttpHeaders"
          attributes:
            $ref: "#/components/schemas/MutableConvertibleValues_Object_"
          body:
            type: array
            items:
              $ref: "#/components/schemas/AddAction.AddActionResult"
          bodyWriter:
            nullable: true
            allOf:
            - $ref: "#/components/schemas/MessageBodyWriter_List_AddAction.AddActionResult__"
          characterEncoding:
            type: string
          locale:
            type: string
          contentLength:
            type: integer
            format: int64
          contentType:
            $ref: "#/components/schemas/MediaType"
    HttpResponse_List_AddAction.AddActionResult__:
      required:
      - attributes
      type: object
      allOf:
      - $ref: "#/components/schemas/HttpMessage_List_AddAction.AddActionResult__"
      - $ref: "#/components/schemas/MutableAttributeHolder"
      - $ref: "#/components/schemas/AttributeHolder"
      - type: object
        properties:
          attributes:
            $ref: "#/components/schemas/MutableConvertibleValues_Object_"
          status:
            $ref: "#/components/schemas/HttpStatus"
          cookies:
            $ref: "#/components/schemas/Cookies"
    HttpStatus:
      type: string
      enum:
      - CONTINUE
      - SWITCHING_PROTOCOLS
      - PROCESSING
      - EARLY_HINTS
      - OK
      - CREATED
      - ACCEPTED
      - NON_AUTHORITATIVE_INFORMATION
      - NO_CONTENT
      - RESET_CONTENT
      - PARTIAL_CONTENT
      - MULTI_STATUS
      - ALREADY_IMPORTED
      - IM_USED
      - MULTIPLE_CHOICES
      - MOVED_PERMANENTLY
      - FOUND
      - SEE_OTHER
      - NOT_MODIFIED
      - USE_PROXY
      - SWITCH_PROXY
      - TEMPORARY_REDIRECT
      - PERMANENT_REDIRECT
      - BAD_REQUEST
      - UNAUTHORIZED
      - PAYMENT_REQUIRED
      - FORBIDDEN
      - NOT_FOUND
      - METHOD_NOT_ALLOWED
      - NOT_ACCEPTABLE
      - PROXY_AUTHENTICATION_REQUIRED
      - REQUEST_TIMEOUT
      - CONFLICT
      - GONE
      - LENGTH_REQUIRED
      - PRECONDITION_FAILED
      - REQUEST_ENTITY_TOO_LARGE
      - REQUEST_URI_TOO_LONG
      - UNSUPPORTED_MEDIA_TYPE
      - REQUESTED_RANGE_NOT_SATISFIABLE
      - EXPECTATION_FAILED
      - I_AM_A_TEAPOT
      - ENHANCE_YOUR_CALM
      - MISDIRECTED_REQUEST
      - UNPROCESSABLE_ENTITY
      - LOCKED
      - FAILED_DEPENDENCY
      - TOO_EARLY
      - UPGRADE_REQUIRED
      - PRECONDITION_REQUIRED
      - TOO_MANY_REQUESTS
      - REQUEST_HEADER_FIELDS_TOO_LARGE
      - NO_RESPONSE
      - BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS
      - UNAVAILABLE_FOR_LEGAL_REASONS
      - REQUEST_HEADER_TOO_LARGE
      - INTERNAL_SERVER_ERROR
      - NOT_IMPLEMENTED
      - BAD_GATEWAY
      - SERVICE_UNAVAILABLE
      - GATEWAY_TIMEOUT
      - HTTP_VERSION_NOT_SUPPORTED
      - VARIANT_ALSO_NEGOTIATES
      - INSUFFICIENT_STORAGE
      - LOOP_DETECTED
      - BANDWIDTH_LIMIT_EXCEEDED
      - NOT_EXTENDED
      - NETWORK_AUTHENTICATION_REQUIRED
      - CONNECTION_TIMED_OUT
    MediaType:
      required:
      - name
      - parametersMap
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        subtype:
          type: string
        extension:
          type: string
        parameters:
          $ref: "#/components/schemas/OptionalValues_String_"
        parametersMap:
          type: object
          additionalProperties:
            type: string
        quality:
          type: string
        qualityAsNumber:
          type: number
        version:
          type: string
        charset:
          type: string
          nullable: true
        textBased:
          type: boolean
    MessageBodyWriter_List_AddAction.AddActionResult__:
      type: object
      properties:
        blocking:
          type: boolean
    MutableAttributeHolder:
      required:
      - attributes
      type: object
      allOf:
      - $ref: "#/components/schemas/AttributeHolder"
      - type: object
        properties:
          attributes:
            $ref: "#/components/schemas/MutableConvertibleValues_Object_"
    MutableConvertibleValues_Object_:
      type: object
      allOf:
      - $ref: "#/components/schemas/ConvertibleValues_Object_"
      - $ref: "#/components/schemas/ConversionServiceProvider"
      - type: object
        properties:
          conversionService:
            $ref: "#/components/schemas/ConversionService"
    OptionalValues_String_:
      type: object
      properties:
        empty:
          type: boolean
    SameSite:
      type: string
      enum:
      - Lax
      - Strict
      - None
      x-enum-varnames:
      - Lax
      - Strict
      - None
