openapi: 3.0.1
info:
  title: oda-actions-service
  version: 1.0.0
paths:
  /actions:
    get:
      operationId: getActions
      parameters:
      - name: recipientId
        in: query
        required: true
        explode: false
        schema:
          type: string
      - name: game
        in: query
        explode: false
        schema:
          type: string
          nullable: true
      - name: enabled
        in: query
        explode: false
        schema:
          type: boolean
          nullable: true
      - name: category
        in: query
        explode: false
        schema:
          type: string
          nullable: true
      - name: provider
        in: query
        explode: false
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: getActions 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActionController.ActionDto"
  /actions/commands/addActions:
    post:
      operationId: addAction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddAction.AddActionsCommand"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddAction.AddActionResult"
  /actions/commands/deleteActions:
    post:
      operationId: deleteActions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteActions.DeleteActionsCommand"
        required: true
      responses:
        "200":
          description: deleteActions 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteActions.DeleteActionsResult"
  /actions/commands/disableActions:
    post:
      operationId: disableActions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DisableActions.DisableActionsCommand"
        required: true
      responses:
        "200":
          description: disableActions 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DisableActions.DisableActionsResult"
  /actions/commands/enableActions:
    post:
      operationId: enableActions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnableActions.EnableActionsCommand"
        required: true
      responses:
        "200":
          description: enableActions 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnableActions.EnableActionsResult"
components:
  schemas:
    ActionController.ActionDto:
      required:
      - category
      - enabled
      - game
      - id
      - name
      - payload
      - price
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          $ref: "#/components/schemas/Amount"
        category:
          type: string
        game:
          type: string
        enabled:
          type: boolean
        payload:
          type: object
          additionalProperties:
            type: object
    AddAction.ActionParameter:
      required:
      - displayName
      - name
      - type
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        type:
          type: string
    AddAction.AddActionResult:
      required:
      - action
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        action:
          $ref: "#/components/schemas/ActionController.ActionDto"
    AddAction.AddActionsCommand:
      required:
      - actions
      type: object
      properties:
        actions:
          type: array
          items:
            $ref: "#/components/schemas/AddAction.NewAction"
    AddAction.NewAction:
      required:
      - category
      - game
      - name
      - parameters
      - payload
      - price
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        game:
          type: string
        price:
          $ref: "#/components/schemas/Amount"
        payload:
          type: object
          additionalProperties:
            type: object
        parameters:
          type: array
          items:
            $ref: "#/components/schemas/AddAction.ActionParameter"
    Amount:
      required:
      - currency
      - major
      - minor
      type: object
      properties:
        minor:
          type: integer
          format: int32
        major:
          type: integer
          format: int32
        currency:
          type: string
    DeleteActions.DeleteActionsCommand:
      type: object
      properties:
        category:
          type: string
          nullable: true
        provider:
          type: string
          nullable: true
        ids:
          type: array
          nullable: true
          items:
            type: string
    DeleteActions.DeleteActionsResult:
      required:
      - ids
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        ids:
          type: array
          items:
            type: string
    DisableActions.DisableActionsCommand:
      type: object
      properties:
        category:
          type: string
          nullable: true
        provider:
          type: string
          nullable: true
        game:
          type: string
          nullable: true
        ids:
          type: array
          nullable: true
          items:
            type: string
    DisableActions.DisableActionsResult:
      required:
      - ids
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        ids:
          type: array
          items:
            type: string
    EnableActions.EnableActionsCommand:
      type: object
      properties:
        category:
          type: string
          nullable: true
        provider:
          type: string
          nullable: true
        game:
          type: string
          nullable: true
        ids:
          type: array
          nullable: true
          items:
            type: string
    EnableActions.EnableActionsResult:
      required:
      - ids
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        ids:
          type: array
          items:
            type: string
