openapi: 3.0.1
info:
  title: oda-streamelements-service
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 0.2.0
paths:
  /streamelements/channels/{channel}:
    get:
      operationId: getChannel
      parameters:
      - name: channel
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getChannel 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamElementsChannelView"
  /streamelements/session:
    get:
      operationId: getSession
      responses:
        "200":
          description: getSession 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamElementsSessionView"
components:
  schemas:
    StreamElementsChannelView:
      required:
      - _id
      - alias
      - avatar
      - broadcasterType
      - displayName
      - inactive
      - isPartner
      - profile
      - provider
      - providerId
      - suspended
      - username
      type: object
      properties:
        profile:
          $ref: "#/components/schemas/StreamElementsChannelView.Profile"
        _id:
          type: string
        isPartner:
          type: boolean
        providerId:
          type: string
        displayName:
          type: string
        username:
          type: string
        avatar:
          type: string
        suspended:
          type: boolean
        provider:
          type: string
        broadcasterType:
          type: string
        alias:
          type: string
        inactive:
          type: boolean
    StreamElementsChannelView.Profile:
      required:
      - headerImage
      - title
      type: object
      properties:
        title:
          type: string
        headerImage:
          type: string
    StreamElementsSessionView:
      required:
      - channel
      - session
      type: object
      properties:
        channel:
          $ref: "#/components/schemas/StreamElementsSessionView.Channel"
        session:
          $ref: "#/components/schemas/StreamElementsSessionView.Session"
    StreamElementsSessionView.Channel:
      required:
      - username
      type: object
      properties:
        username:
          type: string
    StreamElementsSessionView.Data:
      required:
      - follower-latest
      - tip-goal
      - tip-latest
      type: object
      properties:
        tip-latest:
          $ref: "#/components/schemas/StreamElementsSessionView.Tip"
        tip-goal:
          $ref: "#/components/schemas/StreamElementsSessionView.Tip"
        follower-latest:
          $ref: "#/components/schemas/StreamElementsSessionView.Follower"
    StreamElementsSessionView.Follower:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    StreamElementsSessionView.Session:
      required:
      - data
      type: object
      properties:
        data:
          $ref: "#/components/schemas/StreamElementsSessionView.Data"
    StreamElementsSessionView.Tip:
      required:
      - amount
      - name
      type: object
      properties:
        name:
          type: string
        amount:
          type: integer
          format: int64
