openapi: 3.0.1
info:
  title: oda-subscriptions-service
  version: 1.0.0
paths:
  /subscriptions/commands/add-queue-subscription:
    post:
      summary: Subscribe to events
      description: Creates a new subscription
      operationId: addSubscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddSubscription.AddSubscriptionCommand"
        required: true
      responses:
        "200":
          description: Subscription successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
components:
  schemas:
    AddSubscription.AddSubscriptionCommand:
      required:
      - events
      type: object
      properties:
        events:
          type: array
          items:
            type: string
    Void:
      type: object
