openapi: 3.0.1
info:
  title: oda-streamelements-service
  version: 1.0.0
paths:
  /:
    get:
      operationId: getSession
      responses:
        "200":
          description: getSession 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamElementsSessionView"
components:
  schemas:
    StreamElementsSessionView:
      required:
      - channel
      - session
      type: object
      properties:
        channel:
          $ref: "#/components/schemas/StreamElementsSessionView.Channel"
        session:
          $ref: "#/components/schemas/StreamElementsSessionView.Session"
    StreamElementsSessionView.Channel:
      required:
      - username
      type: object
      properties:
        username:
          type: string
    StreamElementsSessionView.Data:
      required:
      - tip-goal
      - tip-latest
      type: object
      properties:
        tip-latest:
          $ref: "#/components/schemas/StreamElementsSessionView.Tip"
        tip-goal:
          $ref: "#/components/schemas/StreamElementsSessionView.Tip"
    StreamElementsSessionView.Session:
      required:
      - data
      type: object
      properties:
        data:
          $ref: "#/components/schemas/StreamElementsSessionView.Data"
    StreamElementsSessionView.Tip:
      required:
      - amount
      - name
      type: object
      properties:
        name:
          type: string
        amount:
          type: integer
          format: int64
