# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build npm packages

on:
  workflow_dispatch:

permissions: write-all

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@opendonationassistant"

      - name: Generate packages
        run: npm install && npm run generate

      - name: Install npm package
        run: npm install
        working-directory: "generated/paywall-service"

      - uses: JS-DevTools/npm-publish@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          registry: "https://npm.pkg.github.com"
          package: "generated/paywall-service"

      - name: Install npm package
        run: npm install
        working-directory: "generated/widget-service"

      - uses: JS-DevTools/npm-publish@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          registry: "https://npm.pkg.github.com"
          package: "generated/widget-service"

      # - name: Install merged client
      #   run: npm install
      #   working-directory: "generated/client"
      #
      # - uses: JS-DevTools/npm-publish@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     token: "${{ secrets.GITHUB_TOKEN }}"
      #     registry: "https://npm.pkg.github.com"
      #     package: "generated/client"
