# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build npm packages

on:
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install npm package
        run: npm install
        working-directory: "generated/paywall-service"

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
          package: "./generated/paywall-service"
